import { Language, Translations, Theme } from './types';

export const SLOGANS = [
  "Speed thrills but kills.",
  "Don't use mobile phone while driving.",
  "Wear a helmet, save your life.",
  "Better late than never.",
  "Safety starts with you.",
  "Say no to corruption, commit to the nation.",
  "Corruption is a cancer that eats away at a citizen's faith in democracy.",
  "Be honest, be bold, be the change.",
  "Integrity is doing the right thing, even when no one is watching.",
  "Your honesty is your strength.",
  "Drive safe, stay safe.",
  "Honesty pays, corruption stays.",
  "Follow traffic rules, avoid accidents.",
  "Vigilance is the price of liberty."
];

export const SERVICE_CATEGORIES = {
  "LICENCE RELATED": [
    "MCWG", "MCWOG", "LMV", "TRAINING ONLY", "BADGE", "HTV", "CONDUCTOR LICENCE",
    "RENEWAL OF DL/CL", "REVALUATION", "CHANGE OF ADDRESS", "CHANGE OF NAME",
    "DUPLICATE DL", "IDPL", "CLUBBING", "EDIT PARTICULARS", "OTHERS (DL)"
  ],
  "VEHICLE RELATED": [
    "NEW REGISTRATION", "TEMP REGISTRATION", "RE-REGISTRATION", "TRANSFER OF OWNERSHIP",
    "HYPOTHECATION TERMINATION", "HYPOTHECATION ADDITION", "HYPOTHECATION CONTINUATION",
    "DUPLICATE RC", "CHANGE OF ADDRESS IN RC", "CONVECTION", "ALTERATIONS",
    "FITNESS CERTIFICATE", "NOC", "MODIFY", "OTHERS (RC)"
  ],
  "PERMIT RELATED": [
    "FRESH PERMIT", "RENEWAL OF PERMIT", "SURRENDER OF PERMIT",
    "CHANGE OF ADDRESS IN PERMIT", "TEMP PERMIT", "TRANSFER OF PERMIT", "OTHERS (PERMIT)"
  ],
  "TAX / CHALLAN": [
    "MV TAX", "GREEN TAX", "CHALLAN", "BALANCE TAX", "LIFE TAX", "BLOCKLISTED", "OTHER (TAX)"
  ]
};

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    setupTitle: "BUSINESS PROFILE SETUP",
    businessName: "BUSINESS NAME",
    mobileNumber: "BUSINESS MOBILE NUMBER",
    email: "BUSINESS MAIL",
    address: "BUSINESS ADDRESS",
    gstNumber: "GST NUMBER",
    optional: "(Optional)",
    logoUpload: "BUSINESS LOGO",
    qrCodesTitle: "QR CODES",
    qrMandatory: "Minimum 1 upload mandatory",
    submit: "SUBMIT",
    language: "Language",
    customerDetails: "CUSTOMER DETAILS",
    customerName: "CUSTOMER NAME",
    customerMobile: "MOBILE NUMBER",
    customerEmail: "MAIL",
    idNo: "VEHICLE NO / DL NO / ANY ID",
    serviceNeeds: "SERVICE NEEDS",
    searchServices: "Search services...",
    selectedServices: "SELECTED SERVICES",
    price: "Price",
    gstPercent: "GST %",
    total: "Total",
    amountPaid: "Amount Paid",
    balance: "Balance Amount",
    pending: "Pending Amount",
    save: "SAVE",
    editProfile: "Edit Profile",
    history: "History",
    logout: "Logout",
    theme: "Theme",
    historyTitle: "TRANSACTION HISTORY",
    noTransactions: "No transactions found.",
    date: "Date",
    searchPlaceholder: "Search name, mobile, vehicle...",
    unpaidFilter: "Unpaid Only",
    allFilter: "All Transactions",
    downloadAll: "Download All (JSON)",
    clearAll: "Clear All History",
    transactionDetail: "TRANSACTION DETAIL",
    printReceipt: "Print Receipt",
    markAsPaid: "Mark as Fully Paid",
    callCustomer: "Call Customer",
    confirmClear: "Are you sure you want to clear all history? This cannot be undone.",
    confirmPaid: "Confirm this transaction as fully paid?",
    themeSelection: "Theme Selection",
    selectTheme: "Select Theme",
    successTitle: "TRANSACTION SUCCESSFUL",
    downloadMonthWise: "Download Month-wise (PDF)",
    downloadAllPDF: "Download All (PDF)",
    selectMonth: "Select Month",
    selectYear: "Select Year",
    download: "Download",
    cancel: "Cancel",
    noTransactionsMonth: "No transactions found for selected month."
  },
  ta: {
    setupTitle: "வணிக சுயவிவர அமைப்பு",
    businessName: "வணிகப் பெயர்",
    mobileNumber: "வணிக மொபைல் எண்",
    email: "வணிக மின்னஞ்சல்",
    address: "வணிக முகவரி",
    gstNumber: "ஜிஎஸ்டி எண்",
    optional: "(விருப்பமானது)",
    logoUpload: "வணிக லோகோ",
    qrCodesTitle: "QR குறியீடுகள்",
    qrMandatory: "குறைந்தது 1 பதிவேற்றம் கட்டாயம்",
    submit: "சமர்ப்பி",
    language: "மொழி",
    customerDetails: "வாடிக்கையாளர் விவரங்கள்",
    customerName: "வாடிக்கையாளர் பெயர்",
    customerMobile: "மொபைல் எண்",
    customerEmail: "மின்னஞ்சல்",
    idNo: "வாகன எண் / டிஎல் எண் / ஏதேனும் ஐடி",
    serviceNeeds: "சேவை தேவைகள்",
    searchServices: "சேவைகளைத் தேடு...",
    selectedServices: "தேர்ந்தெடுக்கப்பட்ட சேவைகள்",
    price: "விலை",
    gstPercent: "ஜிஎஸ்டி %",
    total: "மொத்தம்",
    amountPaid: "செலுத்தப்பட்ட தொகை",
    balance: "மீதமுள்ள தொகை",
    pending: "நிலுவையில் உள்ள தொகை",
    save: "சேமி",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    history: "வரலாறு",
    logout: "வெளியேறு",
    theme: "தீம்",
    historyTitle: "பரிவர்த்தனை வரலாறு",
    noTransactions: "பரிவர்த்தனைகள் எதுவும் இல்லை.",
    date: "தேதி",
    searchPlaceholder: "பெயர், மொபைல், வாகனம் தேடு...",
    unpaidFilter: "செலுத்தப்படாதவை மட்டும்",
    allFilter: "அனைத்து பரிவர்த்தனைகள்",
    downloadAll: "அனைத்தையும் பதிவிறக்கு (JSON)",
    clearAll: "வரலாற்றை அழி",
    transactionDetail: "பரிவர்த்தனை விவரம்",
    printReceipt: "ரசீது அச்சிடு",
    markAsPaid: "முழுமையாக செலுத்தப்பட்டதாகக் குறிக்கவும்",
    callCustomer: "வாடிக்கையாளரை அழைக்கவும்",
    confirmClear: "நிச்சயமாக வரலாற்றை அழிக்க வேண்டுமா? இதை மாற்ற முடியாது.",
    confirmPaid: "இந்த பரிவர்த்தனை முழுமையாக செலுத்தப்பட்டதா?",
    themeSelection: "தீம் தேர்வு",
    selectTheme: "தீம் தேர்ந்தெடுக்கவும்",
    successTitle: "பரிவர்த்தனை வெற்றி",
    downloadMonthWise: "மாதாந்திர பதிவிறக்கம் (PDF)",
    downloadAllPDF: "அனைத்தையும் பதிவிறக்கு (PDF)",
    selectMonth: "மாதத்தைத் தேர்ந்தெடுக்கவும்",
    selectYear: "ஆண்டைத் தேர்ந்தெடுக்கவும்",
    download: "பதிவிறக்கு",
    cancel: "ரத்துசெய்",
    noTransactionsMonth: "தேர்ந்தெடுக்கப்பட்ட மாதத்தில் பரிவர்த்தனைகள் எதுவும் இல்லை."
  },
  hi: {
    setupTitle: "व्यवसाय प्रोफ़ाइल सेटअप",
    businessName: "व्यवसाय का नाम",
    mobileNumber: "व्यवसाय मोबाइल नंबर",
    email: "व्यवसाय मेल",
    address: "व्यवसाय का पता",
    gstNumber: "जीएसटी नंबर",
    optional: "(वैकल्पिक)",
    logoUpload: "व्यवसाय लोगो",
    qrCodesTitle: "QR कोड",
    qrMandatory: "न्यूनतम 1 अपलोड अनिवार्य",
    submit: "जमा करें",
    language: "भाषा",
    customerDetails: "ग्राहक विवरण",
    customerName: "ग्राहक का नाम",
    customerMobile: "मोबाइल नंबर",
    customerEmail: "मेल",
    idNo: "वाहन नंबर / डीएल नंबर / कोई आईडी",
    serviceNeeds: "सेवा आवश्यकताएं",
    searchServices: "सेवाएं खोजें...",
    selectedServices: "चयनित सेवाएं",
    price: "कीमत",
    gstPercent: "जीएसटी %",
    total: "कुल",
    amountPaid: "भुगतान की गई राशि",
    balance: "शेष राशि",
    pending: "लंबित राशि",
    save: "सहेजें",
    editProfile: "प्रोफ़ाइल संपादित करें",
    history: "इतिहास",
    logout: "लॉगआउट",
    theme: "थीम",
    historyTitle: "लेन-देन इतिहास",
    noTransactions: "कोई लेन-देन नहीं मिला।",
    date: "तारीख",
    searchPlaceholder: "नाम, मोबाइल, वाहन खोजें...",
    unpaidFilter: "केवल बकाया",
    allFilter: "सभी लेन-देन",
    downloadAll: "सभी डाउनलोड करें (JSON)",
    clearAll: "इतिहास साफ़ करें",
    transactionDetail: "लेन-देन विवरण",
    printReceipt: "रसीद प्रिंट करें",
    markAsPaid: "पूर्ण भुगतान के रूप में चिह्नित करें",
    callCustomer: "ग्राहक को कॉल करें",
    confirmClear: "क्या आप वाकई सारा इतिहास साफ़ करना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता।",
    confirmPaid: "क्या इस लेन-देन को पूर्ण भुगतान के रूप में पुष्टि करें?",
    themeSelection: "थीम चयन",
    selectTheme: "थीम चुनें",
    successTitle: "लेन-देन सफल",
    downloadMonthWise: "मासिक डाउनलोड (PDF)",
    downloadAllPDF: "सभी डाउनलोड करें (PDF)",
    selectMonth: "महीना चुनें",
    selectYear: "वर्ष चुनें",
    download: "डाउनलोड",
    cancel: "रद्द करें",
    noTransactionsMonth: "चयनित महीने के लिए कोई लेन-देन नहीं मिला।"
  },
  ml: {
    setupTitle: "ബിസിനസ് പ്രൊഫൈൽ സജ്ജീകരണം",
    businessName: "ബിസിനസ്സ് പേര്",
    mobileNumber: "ബിസിനസ്സ് മൊബൈൽ നമ്പർ",
    email: "ബിസിനസ്സ് മെയിൽ",
    address: "ബിസിനസ്സ് വിലാസം",
    gstNumber: "ജിഎസ്ടി നമ്പർ",
    optional: "(ഓപ്ഷണൽ)",
    logoUpload: "ബിസിനസ്സ് ലോഗോ",
    qrCodesTitle: "QR കോഡുകൾ",
    qrMandatory: "കുറഞ്ഞത് 1 അപ്‌ലോഡ് നിർബന്ധമാണ്",
    submit: "സമർപ്പിക്കുക",
    language: "ഭാഷ",
    customerDetails: "ഉപഭോക്തൃ വിശദാംശങ്ങൾ",
    customerName: "ഉപഭോക്താവിന്റെ പേര്",
    customerMobile: "മൊബൈൽ നമ്പർ",
    customerEmail: "മെയിൽ",
    idNo: "വാഹന നമ്പർ / ഡിഎൽ നമ്പർ / ഏതെങ്കിലും ഐഡി",
    serviceNeeds: "സേവന ആവശ്യങ്ങൾ",
    searchServices: "സേവനങ്ങൾ തിരയുക...",
    selectedServices: "തിരഞ്ഞെടുത്ത സേവനങ്ങൾ",
    price: "വില",
    gstPercent: "ജിഎസ്ടി %",
    total: "ആകെ",
    amountPaid: "അടച്ച തുക",
    balance: "ബാക്കി തുക",
    pending: "കുടിശ്ശിക തുക",
    save: "സേവ് ചെയ്യുക",
    editProfile: "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
    history: "ചരിത്രം",
    logout: "ലോഗൗട്ട്",
    theme: "തീം",
    historyTitle: "ഇടപാട് ചരിത്രം",
    noTransactions: "ഇടപാടുകളൊന്നും കണ്ടെത്തിയില്ല.",
    date: "തിയതി",
    searchPlaceholder: "പേര്, മൊബൈൽ, വാഹനം തിരയുക...",
    unpaidFilter: "കുടിശ്ശിക മാത്രം",
    allFilter: "എല്ലാ ഇടപാടുകളും",
    downloadAll: "എല്ലാം ഡൗൺലോഡ് ചെയ്യുക (JSON)",
    clearAll: "ചരിത്രം മായ്ക്കുക",
    transactionDetail: "ഇടപാട് വിവരം",
    printReceipt: "രസീത് പ്രിന്റ് ചെയ്യുക",
    markAsPaid: "പൂർണ്ണമായി അടച്ചതായി അടയാളപ്പെടുത്തുക",
    callCustomer: "ഉപഭോക്താവിനെ വിളിക്കുക",
    confirmClear: "ചരിത്രം മായ്ക്കാൻ ഉറപ്പാണോ? ഇത് മാറ്റാൻ കഴിയില്ല.",
    confirmPaid: "ഈ ഇടപാട് പൂർണ്ണമായി അടച്ചതായി സ്ഥിരീകരിക്കണോ?",
    themeSelection: "തീം തിരഞ്ഞെടുക്കൽ",
    selectTheme: "തീം തിരഞ്ഞെടുക്കുക",
    successTitle: "ഇടപാട് വിജയിച്ചു",
    downloadMonthWise: "മാസാടിസ്ഥാനത്തിൽ ഡൗൺലോഡ് ചെയ്യുക (PDF)",
    downloadAllPDF: "എല്ലാം ഡൗൺലോഡ് ചെയ്യുക (PDF)",
    selectMonth: "മാസം തിരഞ്ഞെടുക്കുക",
    selectYear: "വർഷം തിരഞ്ഞെടുക്കുക",
    download: "ഡൗൺലോഡ്",
    cancel: "റദ്ദാക്കുക",
    noTransactionsMonth: "തിരഞ്ഞെടുത്ത മാസത്തിൽ ഇടപാടുകളൊന്നും കണ്ടെത്തിയില്ല."
  }
};

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'ta', name: 'Tamil' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ml', name: 'Malayalam' }
] as const;

export const THEMES: Theme[] = [
  {
    id: 'dark-purple',
    name: 'Dark Purple Neon',
    colors: {
      primary: '#a855f7',
      secondary: '#1e1b4b',
      background: '#0f172a',
      foreground: '#f8fafc',
      card: '#1e293b',
      border: '#334155',
      input: '#1e293b',
      ring: '#8b5cf6',
      accent: '#38bdf8',
    }
  },
  {
    id: 'black-green',
    name: 'Black & Green Modern',
    colors: {
      primary: '#22c55e',
      secondary: '#171717',
      background: '#000000',
      foreground: '#ffffff',
      card: '#171717',
      border: '#262626',
      input: '#171717',
      ring: '#22c55e',
      accent: '#4ade80',
    }
  },
  {
    id: 'dark-blue',
    name: 'Dark Blue Finance',
    colors: {
      primary: '#3b82f6',
      secondary: '#1e293b',
      background: '#020617',
      foreground: '#f8fafc',
      card: '#0f172a',
      border: '#1e293b',
      input: '#0f172a',
      ring: '#3b82f6',
      accent: '#60a5fa',
    }
  },
  {
    id: 'purple-brand',
    name: 'Purple Branding Style',
    colors: {
      primary: '#7c3aed',
      secondary: '#f5f3ff',
      background: '#f5f3ff',
      foreground: '#1e1b4b',
      card: '#ffffff',
      border: '#e0e7ff',
      input: '#ffffff',
      ring: '#7c3aed',
      accent: '#a78bfa',
    }
  },
  {
    id: 'red-black',
    name: 'Red & Black Bold',
    colors: {
      primary: '#ef4444',
      secondary: '#171717',
      background: '#0a0a0a',
      foreground: '#ffffff',
      card: '#171717',
      border: '#262626',
      input: '#171717',
      ring: '#ef4444',
      accent: '#f87171',
    }
  },
  {
    id: 'light-minimal',
    name: 'Clean Light Minimal',
    colors: {
      primary: '#64748b',
      secondary: '#f1f5f9',
      background: '#f8fafc',
      foreground: '#0f172a',
      card: '#ffffff',
      border: '#e2e8f0',
      input: '#ffffff',
      ring: '#64748b',
      accent: '#94a3b8',
    }
  }
];
